<?php /* @var $this MageProfis_ManufacturerCategories_Block_Homepage */ ?>
<?php $_manufacturers = $this->getManufacturers(); ?>
<?php $_manufacturers_count = $this->getManufacturers()->count(); ?>

<?php if ($_manufacturers_count): ?>
    <div class="section-title manufacturers-title"><?php echo Mage::getStoreConfig('manufacturercategories/homepage/heading'); ?></div>
    <div id="manufacturers">
        <?php foreach ($_manufacturers as $_brand): ?>
            <div class="manufacturer">
                <a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>">
                    <img src="<?php echo Mage::getUrl('media/catalog/category') . $_brand->getBrandLogo(); ?>" alt="<?php echo $_brand->getName(); ?>"/>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="all-brands-link">
        <a href="<?php echo $this->getAllBrandsUrl(); ?>">
            <?php echo $this->__('show all brands') ?>
        </a>
    </div>
<?php endif; ?>
<script type="text/javascript">
    jQuery(document).ready(function () {
        var topsellers = jQuery("#manufacturers");
        topsellers.owlCarousel({
            navigation: false, // Show next and prev buttons
            slideSpeed: 300,
            paginationSpeed: 400,
            pagination: false,
            items: 7
        });
        jQuery('.topsellers .owl-arrow').appendTo('.topsellers-slider');
    });
    jQuery('.topsellers  .owl-arrow').click(function () {
        var owl = jQuery(".topsellers-slider").data('owlCarousel');
        if (jQuery(this).hasClass('prev')) {
            owl.prev();
        } else if (jQuery(this).hasClass('next')) {
            owl.next();
        }
    });
</script>