<?php /* @var $this MageProfis_ManufacturerCategories_Block_Brands */ ?>
<?php $allbrands = Mage::registry('current_category'); ?>
<?php $brands = $this->getManufacturers(); ?>
<?php $brandscount = $this->getManufacturers()->count(); ?>

<?php if ($brandscount > 0): ?>
    <div class="all-brands-list row">
        <?php foreach ($this->getManufacturers() as $_brand): ?>
            <?php //Zend_Debug::dump($_brand->getData()); ?>
            <div class="brand col-xs-2">
                <a href="<?php echo $_brand->getUrl() ?>" title="<?php echo $_brand->getName() ?>">
                    <?php if ($_brand->getBrandLogo() != ""): ?>
                        <img src="<?php echo Mage::getUrl('media/catalog/category') . $_brand->getBrandLogo() ?>" alt="<?php echo $_brand->getName(); ?>" />
                    <?php endif; ?>
                    <div class="brand-name"><?php echo $_brand->getName(); ?></div>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

<?php if ($allbrands->getBrandLongDescription() != ""): ?>
    <div class="category-seo-text std all-brands-page-desc">
        <?php echo $allbrands->getBrandLongDescription(); ?>
    </div>
<?php endif; ?>